<div class="modal fade" id="applyModal" tabindex="-1" role="dialog" aria-labelledby="applyModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">申请开店</h4>
            </div>
            <div class="modal-body">
                <p>请您正确填写您的姓名,联系方式及地址,我们的工作人员会尽快与您联系核对您的信息.(注:1-2个工作日内.)</p>
                <form>
                    <div class="form-group">
                        <label for="recipient-name" class="control-label">姓名:</label>
                        <input type="text" class="form-control" id="apply_name">
                    </div>

                    <div class="form-group">
                        <label for="message-text" class="control-label">联系电话:</label>
                        <input type="number" class="form-control" id="apply_phone">
                    </div>

                    <div class="form-group">
                        <label for="message-text" class="control-label">电子邮箱:</label>
                        <input type="email" class="form-control" id="apply_email">
                    </div>

                    <div class="form-group">
                        <label for="message-text" class="control-label">联系地址:</label>
                        <input type="text" class="form-control" id="apply_address">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" id="apply_btn">发送</button>
            </div>
        </div>
    </div>
</div>