<!DOCTYPE html>
<html>
<head>
    <title><?php echo !empty($_page_title) ? $_page_title : '北京周边采摘 农家乐 散养柴鸡蛋.';?></title>
    <meta name="keywords" content="<?php echo !empty($_page_keywords) ? $_page_keywords : '北京周边采摘 农家乐 散养柴鸡蛋.';?>">
    <meta name="description" content="<?php echo !empty($_page_description) ? $_page_description : '北京周边采摘 农家乐 散养柴鸡蛋.';?>">

    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <meta charset="utf-8">

    <link href="/static/second_asset/common/header.css" rel="stylesheet" type="text/css">
    <link href="/static/second_asset/common/h.css" rel="stylesheet" type="text/css">
    <link href="/static/second_asset/common/text.css" rel="stylesheet" type="text/css">

    <link href="/static/second_asset/common/row-space.css" rel="stylesheet" type="text/css">

    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="/static/second_asset/common/footer.css" rel="stylesheet" type="text/css" media="screen">

    <script src="/static/admin_lte/plugins/jQuery/jQuery-2.1.3.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php if(isset($css)){

        foreach($css as $file){
            echo '<link href="'.$file.'" rel="stylesheet" type="text/css" media="screen">';
        }

    }
    ?>

    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "//hm.baidu.com/hm.js?2d15d93a9143a56e71046ffd887d2643";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
    </script>
</head>
<body>