<div class="header">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-5">
                <!-- Link -->
                <a href="/">
                    <!-- Logo area -->
                    <div class="logo">
                        <img class="img-responsive" src="/static/assert/logo.png" alt="">
                        <!-- Heading -->
                        <h1>农曲星</h1>
                        <!-- Paragraph -->
                        <p>北京周边采摘 农家乐 散养柴鸡蛋.</p>
                    </div>
                </a>
            </div>
            <div class="col-md-8 col-sm-7">
                <!-- Navigation -->
                <nav class="navbar navbar-default navbar-right" role="navigation">
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li class="<?=isset($_current_nav_) && 'home' == $_current_nav_ ? 'current' : ''?>">
                                    <a href="/"> 首页</a>
                                </li>
                                <!--
                                <li class="">
                                    <a href="#" class="dropdown-toggle"> 采摘</a>
                                </li>

                                <li class="">
                                    <a href="#"> 农家乐</a>
                                </li>
                                <li class="">
                                    <a href="#" class="">柴鸡蛋</a>
                                </li>
                                -->
                                <li class="<?=isset($_current_nav_) && 'about' == $_current_nav_ ? 'current' : ''?>">
                                    <a href="/index/about"> 关于我们</a>
                                </li>
                                <?php if(true == $_is_login_){?>
                                <li class="<?=isset($_current_nav_) && 'me' == $_current_nav_ ? 'current' : ''?>">
                                    <a href="/index/me" class=""><?=$_user_info_['nickname']?></a>
                                </li>
                                <?php }?>
                            </ul>
                        </div>
                        <!-- /.navbar-collapse -->
                    </div>
                    <!-- /.container-fluid -->
                </nav>
            </div>
        </div>
    </div>
    <!-- / .container -->
</div>