    <!-- Footer Start -->
    <div class="footer padd">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-6">
            <!-- Footer widget -->
            <div class="footer-widget">
              <!-- Logo area -->
              <div class="logo">
                <img class="img-responsive" src="/static/assert/logo.jpg" alt="" />
                <!-- Heading -->
                <h1>农品会</h1>
              </div>
              <!-- Paragraph -->
              <p>我们致力于生态农业的开发与研究,成员多是来自中国农业大学的大学生.我们有先进的科学理论,扎实的动手能力,努力打造一个全新的现代化的农业平台.</p>
              <!--<hr />-->
              <!-- Heading -->
              <!--<h6>On-line Payment Clients</h6>-->
              <!-- Images -->
              <!--
              <a href="#"><img class="payment img-responsive" src="img/payment/2co.gif" alt="" /></a>
              <a href="#"><img class="payment img-responsive" src="img/payment/authorizenet.gif" alt="" /></a>
              <a href="#"><img class="payment img-responsive" src="img/payment/discover.gif" alt="" /></a>
              <a href="#"><img class="payment img-responsive" src="img/payment/egold.gif" alt="" /></a>
              <a href="#"><img class="payment img-responsive" src="img/payment/mastercard.gif" alt="" /></a>
              <a href="#"><img class="payment img-responsive" src="img/payment/paypal.gif" alt="" /></a>
              <a href="#"><img class="payment img-responsive" src="img/payment/visa.gif" alt="" /></a>
              <a href="#"><img class="payment img-responsive" src="img/payment/worldpay.gif" alt="" /></a>
              -->
            </div> <!--/ Footer widget end -->
          </div>

          <div class="clearfix visible-sm"></div>
          <div class="col-md-4 col-sm-6">
            <!-- Footer widget -->
            <div class="footer-widget">
              <!-- Heading -->
              <h4>加入我们</h4>
              <!-- Paragraph -->
              <p>我们致力于追求完美健康的生活.</p>
              <!-- Subscribe form -->
              <form role="form">
                <div class="form-group">
                  <input class="form-control" type="text" placeholder="您的名字" />
                </div>
                <div class="form-group">
                  <input class="form-control" type="email" placeholder="您的邮箱" />
                </div>
                <button class="btn btn-danger" type="button">发送</button>
              </form>
            </div> <!--/ Footer widget end -->
          </div>
          <div class="col-md-4 col-sm-6">
            <!-- Footer widget -->
            <div class="footer-widget">
              <!-- Heading -->
              <h4>联系我们</h4>
              <div class="contact-details">
                <!-- Address / Icon -->
                <i class="fa fa-map-marker br-red"></i> <span>北京市海淀区聂各庄(凤凰岭)<br />(公交346聂各庄)<br />  </span>
                <div class="clearfix"></div>
                <!-- Contact Number / Icon -->
                <i class="fa fa-phone br-green"></i> <span>+暂无</span>
                <div class="clearfix"></div>
                <!-- Email / Icon -->
                <i class="fa fa-envelope-o br-lblue"></i> <span><a href="#">agrovips@163.com</a></span>
                <div class="clearfix"></div>
              </div>
              <!-- Social media icon -->
              <!--
              <div class="social">
                <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
                <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                <a href="#" class="pinterest"><i class="fa fa-pinterest"></i></a>
              </div>
              -->
            </div> <!--/ Footer widget end -->
          </div>
        </div>
        <!-- Copyright -->
        <div class="footer-copyright">
          <!-- Paragraph -->
          <p>&copy; Copyright 2015 <a href="#">农品会</a></p>
        </div>
      </div>
    </div>
    <!-- Footer End -->
        <!-- Scroll to top -->
    <span class="totop"><a href="#"><i class="fa fa-angle-up"></i></a></span>

  </body>
</html>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/static/global/js/jquery.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
