
    <div class="header">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-5">
            <!-- Link -->
            <a href="/">
              <!-- Logo area -->
              <div class="logo">
                <img class="img-responsive" src="static/assert/logo.jpg" alt="" />
                <!-- Heading -->
                <h1>农品会</h1>
                <!-- Paragraph -->
                <p>北京周边采摘 农家乐 散养柴鸡蛋.</p>
              </div>
            </a>
          </div>
          <div class="col-md-8 col-sm-7">
            <!-- Navigation -->
            <nav class="navbar navbar-default navbar-right" role="navigation">
              <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                    <li class="<?php echo isset($currentNav) && 'home' == $currentNav ? 'current' : '';?>">
                      <a href="/"> 首页</a>
                    </li>
                    <li class="<?php echo isset($currentNav) && 'farm' == $currentNav ? 'current' : '';?>">
                      <a href="#" class="dropdown-toggle"> 采摘</a>
                    </li>

                    <li class="<?php echo isset($currentNav) && 'yard' == $currentNav ? 'current' : '';?>">
                      <a href="#"> 农家乐</a>
                    </li>
                    <li class="<?php echo isset($currentNav) && 'egg' == $currentNav ? 'current' : '';?>">
                      <a href="#" class="">柴鸡蛋</a>
                    </li>
                    <li class="<?php echo isset($currentNav) && 'about' == $currentNav ? 'current' : '';?>">
                      <a href="/about"> 关于我们</a>
                    </li>
                  </ul>
                </div>
                <!-- /.navbar-collapse -->
              </div>
              <!-- /.container-fluid -->
            </nav>
          </div>
        </div>
      </div>
      <!-- / .container -->
    </div>
