<!--header-->
<?php
  echo Yaf_View_Simple::render('admin/tpl/header.phtml', array('css' => array('/static/admin/css/shopinfo.css')));
?>
<link rel="stylesheet" type="text/css" href="/static/plugin/uploadify/uploadify.css">
<!--/header-->
      <!--navbar-->
      <?php
        echo Yaf_View_Simple::render('admin/tpl/navbar.phtml');
      ?>
      <!--navbar-->

      <!-- Left side column. contains the logo and sidebar -->
      <!--sidebar-->
      <?php
        echo Yaf_View_Simple::render('admin/tpl/sidebar.phtml');
      ?>
      <!--sidebar-->

      <!-- Right side column. Contains the navbar and content of the page -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            <?=htmlspecialchars($page_title)?>
            <small>Preview</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
            <li><a href="#">商品管理</a></li>
            <li class="active"><?=htmlspecialchars($page_title)?></li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-8">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form">
                  <div class="box-body">
                    <div class="form-group">
                      <label>商品名称</label>
                      <input type="hidden" name="good_id" id="good_id" value="<?=isset($good['id']) ? htmlspecialchars($good['id']) : ''?>">
                      <input type="hidden" name="shop_id" id="shop_id" value="<?=isset($shop_id) ? htmlspecialchars($shop_id) : 0?>">
                      <input type="text" class="form-control" id="good_title" placeholder="请输入商品名称" value="<?=isset($good['title']) ? htmlspecialchars($shop['title']) : ''?>">
                    </div>

                    <div class="form-group">
                      <label>商品简单描述</label>
                      <input type="text" class="form-control" id="good_slogan" placeholder="请输入商品简单描述" value="<?=isset($good['slogan']) ? htmlspecialchars($shop['slogan']) : ''?>">
                    </div>

                    <div class="form-group">
                      <label>库存</label>
                      <input type="text" class="form-control" id="good_stock" placeholder="请输入商品库存" value="<?=isset($good['discount_price']) ? htmlspecialchars($shop['discount_price']) : ''?>">
                    </div>

                    <div class="form-group">
                      <label>价格</label>
                      <input type="text" class="form-control" id="good_price" placeholder="请输入商品价格" value="<?=isset($good['price']) ? htmlspecialchars($shop['price']) : ''?>">
                    </div>

                    <div class="form-group">
                      <label>折后价</label>
                      <input type="text" class="form-control" id="good_d_price" placeholder="请输入商品折后价格" value="<?=isset($good['discount_price']) ? htmlspecialchars($shop['discount_price']) : ''?>">
                    </div>

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="button" class="btn btn-primary" id="submit">保存</button>
                  </div>
                </form>
              </div><!-- /.box -->
            </div><!--/.col (left) -->
          </div>   <!-- /.row -->
        </section>
        <!-- /.content -->

      </div>
      <!-- /.content-wrapper -->

<!--footer-->
<?php
  echo Yaf_View_Simple::render('admin/tpl/footer.phtml');
?>
<!--footer-->
<?php $timestamp = time();?>
<script type="text/javascript">

$("#submit").click(function () {
    var good_title =   $("#good_title").val();
    var good_slogan = $("#good_slogan").val();
    var good_price =    $("#good_price").val();
    var good_d_price  =   $("#good_d_price").val();
    var good_id = $('#good_id').val();
    var shop_id = $('#shop_id').val();

    if(!good_title || !good_slogan || !good_price || !good_d_price || !shop_id){
      alert("您填入的数据不完整,请你检查后重新提交!");
      return false;
    }

    var postData = {
        'good_title':good_title,
        'good_slogan':good_slogan,
        'good_price': good_price,
        'good_d_price': good_d_price,
        'good_id': good_id,
        'shop_id': shop_id
    }
    console.log(postData);//return;


    $.post("/admin/savegood", postData,function(response){
        console.log(response);

        if(0 == response.errno){
          alert('保存成功.');
          location.href = '/admin/goodlist?shop_id=' + shop_id;
        }else{
          alert('好像出问题了.');
        }
    })
})
</script>