<!--header-->
<?php
  echo Yaf_View_Simple::render('admin/tpl/header.phtml', array('css' => array('/static/admin/css/shopinfo.css')));
?>
<link rel="stylesheet" type="text/css" href="/static/plugin/uploadify/uploadify.css">
<!--/header-->
      <!--navbar-->
      <?php
        echo Yaf_View_Simple::render('admin/tpl/navbar.phtml');
      ?>
      <!--navbar-->

      <!-- Left side column. contains the logo and sidebar -->
      <!--sidebar-->
      <?php
        echo Yaf_View_Simple::render('admin/tpl/sidebar.phtml');
      ?>
      <!--sidebar-->

      <!-- Right side column. Contains the navbar and content of the page -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            <?=htmlspecialchars($page_title)?>
            <small>Preview</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
            <li><a href="#">商品管理</a></li>
            <li class="active"><?=htmlspecialchars($page_title)?></li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
          <div class="row">
            <!-- left column -->
            <div class="col-md-8">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form">
                  <div class="box-body">
                    <div class="form-group">
                      <label>商品名称</label>
                      <input type="hidden" name="good_id" id="good_id" value="<?=isset($good_id) ? htmlspecialchars($good_id) : ''?>">
                      <input type="hidden" name="shop_id" id="shop_id" value="<?=isset($shop_id) ? htmlspecialchars($shop_id) : 0?>">
                      <input type="text" class="form-control" id="good_title" placeholder="请输入商品名称.如:【精品草莓采摘】" value="<?=isset($good['title']) ? htmlspecialchars($good['title']) : ''?>">
                    </div>

                    <div class="form-group">
                      <label>商品简单描述</label>
                      <input type="text" class="form-control" id="good_slogan" placeholder="请输入商品简单描述.如: 牛奶草莓,保甜,量大从优" value="<?=isset($good['slogan']) ? htmlspecialchars($good['slogan']) : ''?>">
                    </div>

                    <div class="form-group">
                        <label>商品类别</label>
                        <div></div>
                        <div style="display: inline-block;width: 45%;float: left;">
                            <select class="form-control" id="good_category_id">
                                <!--<option>省/直辖市</option>-->
                                <?php foreach($category as $c_id => $cat){

                                    ?>
                                    <option value="<?=$c_id?>" <?=isset($good) && $c_id == $good['category_id'] ? 'selected="selected"' : ''?>><?=$cat?></option>
                                <?php }?>
                            </select>
                        </div>

                        <div style="display: inline-block;width: 45%;float: left;  line-height: 33px;margin-left: 20px;">
                            <span>请选择商品类别.如:樱桃采摘</span>
                        </div>
                        <div style="clear: both;"></div>
                    </div>

                    <div class="form-group">
                      <label>库存</label>
                      <input type="text" class="form-control" id="good_stock" placeholder="请输入商品库存.如: 2000斤/300盒" value="<?=isset($good['stock']) ? htmlspecialchars($good['stock']) : ''?>">
                    </div>

                    <div class="form-group">
                      <label>价格</label>
                      <input type="text" class="form-control" id="good_price" placeholder="请输入商品价格.如: 200" value="<?=isset($good['price']) ? htmlspecialchars($good['price']) : ''?>">
                    </div>

                    <div class="form-group">
                      <label>折后价</label>
                      <input type="text" class="form-control" id="good_d_price" placeholder="请输入商品折后价格.如: 180" value="<?=isset($good['discount_price']) ? htmlspecialchars($good['discount_price']) : ''?>">
                    </div>

                    <div class="form-group">
                      <label>计价单位</label>
                      <input type="text" class="form-control" id="good_unit" placeholder="请输入商品计价单位.如: 斤/人/次/盒/打" value="<?=isset($good['unit']) ? htmlspecialchars($good['unit']) : ''?>">
                     </div>

                    <div class="form-group">
                      <label>联系人姓名</label>
                      <input type="text" class="form-control" id="good_contactor" placeholder="请输入联系人姓名.如: 李阿姨" value="<?=isset($good['contactor']) ? htmlspecialchars($good['contactor']) : ''?>">
                    </div>

                    <div class="form-group">
                      <label>联系人电话</label>
                      <input type="text" class="form-control" id="good_phone" placeholder="请输入联系人电话.如: 1801012xxx" value="<?=isset($good['phone']) ? htmlspecialchars($good['phone']) : ''?>">
                    </div>

                  </div><!-- /.box-body -->

                  <div class="box-footer">
                    <button type="button" class="btn btn-primary" id="submit">保存</button>
                  </div>
                </form>
              </div><!-- /.box -->
            </div><!--/.col (left) -->
          </div>   <!-- /.row -->
        </section>
        <!-- /.content -->

      </div>
      <!-- /.content-wrapper -->

<!--footer-->
<?php
  echo Yaf_View_Simple::render('admin/tpl/footer.phtml');
?>
<!--footer-->
<?php $timestamp = time();?>
<script type="text/javascript">

$("#submit").click(function () {
    var good_title =   $("#good_title").val();
    var good_slogan = $("#good_slogan").val();
    var good_price =    $("#good_price").val();
    var good_d_price  =   $("#good_d_price").val();
    var good_id = $('#good_id').val();
    var shop_id = $('#shop_id').val();
    var good_stock = $('#good_stock').val();
    var good_contactor = $('#good_contactor').val();
    var good_phone = $('#good_phone').val();
    var good_unit = $("#good_unit").val();
    var good_category_id = $('#good_category_id').val();

    if(!good_title || !good_slogan || !good_price || !good_d_price || !shop_id && !good_contactor || !good_phone){
      alert("您填入的数据不完整,请你检查后重新提交!");
      return false;
    }

    var postData = {
        'good_title':good_title,
        'good_slogan':good_slogan,
        'good_price': good_price,
        'good_d_price': good_d_price,
        'good_stock':good_stock,
        'good_id': good_id,
        'shop_id': shop_id,
        'good_contactor':good_contactor,
        'good_phone':good_phone,
        'good_unit':good_unit,
        'good_category_id':good_category_id
    }
    //console.log(postData);//return;


    $.post("/admin/savegood", postData,function(response){
        console.log(response);

        if(0 == response.errno){
          alert('保存成功.');
          location.href = '/admin/goodlist?shop_id=' + shop_id;
        }else{
          alert('好像出问题了.');
        }
    })
})
</script>