


<!--header-->
<?php
echo Yaf_View_Simple::render('admin/tpl/header.phtml', array('css' => array('/static/admin_lte//plugins/datatables/dataTables.bootstrap.css')));
?>
<link rel="stylesheet" type="text/css" href="/static/plugin/uploadify/uploadify.css">
<!--/header-->
<!--navbar-->
<?php
echo Yaf_View_Simple::render('admin/tpl/navbar.phtml');
?>
<!--navbar-->

<!-- Left side column. contains the logo and sidebar -->
<!--sidebar-->
<?php
echo Yaf_View_Simple::render('admin/tpl/sidebar.phtml');
?>
<!--sidebar-->

<!-- Right side column. Contains the navbar and content of the page -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            我的店铺
            <small>Preview</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
            <li><a href="#">店铺管理</a></li>
            <li class="active">我的店铺</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">

            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Hover Data Table</h3>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline" role="grid">
                            <div class="row">
                                <div class="col-xs-6"></div>
                                <div class="col-xs-6"></div>
                            </div>
                            <table id="example2" class="table table-bordered table-hover dataTable" aria-describedby="example2_info">
                                <thead>
                                <tr role="row"><th class="sorting_asc" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Rendering engine</th><th class="sorting" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Browser</th><th class="sorting" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Platform(s)</th><th class="sorting" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Engine version</th><th class="sorting" role="columnheader" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">CSS grade</th></tr>
                                </thead>

                                <tfoot>
                                <tr><th rowspan="1" colspan="1">Rendering engine</th><th rowspan="1" colspan="1">Browser</th><th rowspan="1" colspan="1">Platform(s)</th><th rowspan="1" colspan="1">Engine version</th><th rowspan="1" colspan="1">CSS grade</th></tr>
                                </tfoot>

                                <tbody role="alert" aria-live="polite" aria-relevant="all"><tr class="odd">
                                    <td class=" sorting_1">Webkit</td>
                                    <td class=" ">Safari 1.2</td>
                                    <td class=" ">OSX.3</td>
                                    <td class=" ">125.5</td>
                                    <td class=" ">A</td>
                                </tr><tr class="even">
                                    <td class=" sorting_1">Webkit</td>
                                    <td class=" ">Safari 1.3</td>
                                    <td class=" ">OSX.3</td>
                                    <td class=" ">312.8</td>
                                    <td class=" ">A</td>
                                </tr><tr class="odd">
                                    <td class=" sorting_1">Webkit</td>
                                    <td class=" ">Safari 2.0</td>
                                    <td class=" ">OSX.4+</td>
                                    <td class=" ">419.3</td>
                                    <td class=" ">A</td>
                                </tr><tr class="even">
                                    <td class=" sorting_1">Webkit</td>
                                    <td class=" ">Safari 3.0</td>
                                    <td class=" ">OSX.4+</td>
                                    <td class=" ">522.1</td>
                                    <td class=" ">A</td>
                                </tr><tr class="odd">
                                    <td class=" sorting_1">Webkit</td>
                                    <td class=" ">OmniWeb 5.5</td>
                                    <td class=" ">OSX.4+</td>
                                    <td class=" ">420</td>
                                    <td class=" ">A</td>
                                </tr><tr class="even">
                                    <td class=" sorting_1">Webkit</td>
                                    <td class=" ">iPod Touch / iPhone</td>
                                    <td class=" ">iPod</td>
                                    <td class=" ">420.1</td>
                                    <td class=" ">A</td>
                                </tr><tr class="odd">
                                    <td class=" sorting_1">Webkit</td>
                                    <td class=" ">S60</td>
                                    <td class=" ">S60</td>
                                    <td class=" ">413</td>
                                    <td class=" ">A</td>
                                </tr></tbody>
                            </table>
                            <div class="row">
                                <div class="col-xs-6"><div class="dataTables_info" id="example2_info">Showing 51 to 57 of 57 entries</div></div>
                                <div class="col-xs-6"><div class="dataTables_paginate paging_bootstrap"><ul class="pagination"><li class="prev"><a href="#">← Previous</a></li><li><a href="#">2</a></li><li><a href="#">3</a></li><li><a href="#">4</a></li><li><a href="#">5</a></li><li class="active"><a href="#">6</a></li><li class="next disabled"><a href="#">Next → </a></li></ul></div></div></div></div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div>


        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>
<!-- /.content-wrapper -->

<!--footer-->
<?php
echo Yaf_View_Simple::render('admin/tpl/footer.phtml');
?>
<!--footer-->
<script type="text/javascript" src="/static/plugin/uploadify/jquery.uploadify.min.js"></script>
<?php $timestamp = time();?>
<script type="text/javascript">

</script>