<!--header-->
<?php
echo Yaf_View_Simple::render('admin/tpl/header.phtml', array('css' => array('/static/admin/css/shopinfo.css')));
?>
<link rel="stylesheet" type="text/css" href="/static/plugin/uploadify/uploadify.css">
<!--/header-->
      <!--navbar-->
      <?php
        echo Yaf_View_Simple::render('admin/tpl/navbar.phtml');
      ?>
      <!--navbar-->

      <!-- Left side column. contains the logo and sidebar -->
      <!--sidebar-->
      <?php
        echo Yaf_View_Simple::render('admin/tpl/sidebar.phtml');
      ?>
      <!--sidebar-->

      <!-- Right side column. Contains the navbar and content of the page -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            <?=htmlspecialchars($page_title)?>
            <small>Preview</small>
          </h1>
          <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
            <li><a href="#">商品管理</a></li>
            <li class="active"><?=htmlspecialchars($page_title)?></li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="btn-group btn-group-lg" role="group" aria-label="Large button group" style="margin-bottom: 10px;width: 100%;" id="goodSegment_box">
                <button type="button" class="btn goodSegment btn-info" style="width: 25%;" data-title="good_intro">产品介绍</button>
                <button type="button" class="btn btn-default goodSegment" style="width: 25%;" data-title="buy_needKnow">购买须知</button>
                <button type="button" class="btn btn-default goodSegment" style="width: 25%;" data-title="buy_detail">订购详情</button>
                <button type="button" class="btn btn-default goodSegment" style="width: 25%;" data-title="use_list">使用流程</button>
            </div>
          <div class="row">
            <!-- left column -->
            <div class="col-md-12">
              <!-- general form elements -->
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form role="form">
                  <div class="box-body">
                      <div class="form-group" id="upload">
                          <input type="hidden" name="shop_id" id="shop_id" value="<?=htmlspecialchars($shop_id)?>">
                          <input type="hidden" name="good_id" id="good_id" value="<?=htmlspecialchars($good_id)?>">
                          <label>产品介绍</label>
                          <input type="file" id="good_photo">
                          <p class="help-block">请选择上传图片</p>
                      </div>

                      <div class="form-group" id="goodPhotoBox">
                          <div class="row">

                          </div>
                      </div>

                      <div class="form-group" id="info_editor" style="display: none;">
                          <label id="segment_title">产品图片</label>
                          <div class="row">
                              <script id="editor" type="text/plain" style="margin-left: 9px;width:99%;height:500px;"></script>
                          </div>
                      </div>

                  </div>
                    <!-- /.box-body -->

                  <div class="box-footer">
                    <button type="button" class="btn btn-primary" id="submit">保存</button>
                  </div>
                </form>
              </div><!-- /.box -->
            </div><!--/.col (left) -->
          </div>   <!-- /.row -->
        </section>
        <!-- /.content -->

      </div>
      <!-- /.content-wrapper -->

<!--footer-->
<?php
  echo Yaf_View_Simple::render('admin/tpl/footer.phtml');
?>
<!--footer-->

<script type="text/javascript">
    var good_intro = '<?=isset($good["good_intro"]) ? $good["good_intro"] : ""?>';
    var buy_needKnow ='<?=isset($good["buy_needKnow"]) ? $good["buy_needKnow"] : ""?>';
    var buy_detail = '<?=isset($good["buy_detail"]) ? $good["buy_detail"] : ""?>';
    var use_list = '<?=isset($good["use_list"]) ? $good["use_list"] : ""?>';
</script>
<script type="text/javascript" charset="utf-8" src="/static/plugin/ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/static/plugin/ueditor/ueditor.all.min.js"> </script>
<script type="text/javascript" charset="utf-8" src="/static/plugin/ueditor/lang/zh-cn/zh-cn.js"></script>

<script type="text/javascript" src="/static/plugin/uploadify/jquery.uploadify.min.js"></script>
<script type="text/javascript" src="/static/admin/js/goodMoreInfo.js"></script>


