<!--header-->
<?php
echo Yaf_View_Simple::render('admin/tpl/header.phtml');
?>
<!--/header-->
<!--navbar-->
<?php
echo Yaf_View_Simple::render('admin/tpl/navbar.phtml');
?>
<!--navbar-->

<!-- Left side column. contains the logo and sidebar -->
<!--sidebar-->
<?php
echo Yaf_View_Simple::render('admin/tpl/sidebar.phtml');
?>
<!--sidebar-->

<!-- Right side column. Contains the navbar and content of the page -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            管理角色授权
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
            <li><a href="#">管理角色授权</a></li>
            <li class="active">角色授权</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

<p>
<?php
    Html::showFlash();
?>
</p>
<p>当前角色: <span class="label label-success"><?php echo $tpl['role']['description']; ?></span></p>
    <form class="form-inline" action="rbac_roles_assign" method="post">
        <input type="hidden" name="rid" value="<?php echo $tpl['rid']; ?>" />

<?php
$permissions_4_role = array_values($tpl['permissions_4_role']);
foreach ($tpl['permissions'] as $pid => $ps)
{
?>
        <div class="checkbox">
            <label>
            <input type="checkbox" name="ps[<?php echo $pid?>]" value="<?php echo $pid; ?>" <?php echo in_array($pid, $permissions_4_role) ? 'checked' : ''; ?>/>
            <span class="label label-primary"><?php echo $ps['description']; ?></span>
            (<?php echo $ps['title']; ?>)&nbsp;
            </label>
            &nbsp;&nbsp;
        </div>
<?php
}
?>
        <button type="submit" class="btn btn-default">授权</button>
    </form>
    </section>
</div>
<!-- /.content-wrapper -->

<!--footer-->
<?php
echo Yaf_View_Simple::render('admin/tpl/footer.phtml');
?>
