<!--header-->
<?php
echo Yaf_View_Simple::render('admin/tpl/header.phtml');
?>
<!--/header-->
<!--navbar-->
<?php
echo Yaf_View_Simple::render('admin/tpl/navbar.phtml');
?>
<!--navbar-->

<!-- Left side column. contains the logo and sidebar -->
<!--sidebar-->
<?php
echo Yaf_View_Simple::render('admin/tpl/sidebar.phtml');
?>
<!--sidebar-->

<!-- Right side column. Contains the navbar and content of the page -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            管理用户角色分配
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
            <li><a href="#">管理用户角色分配</a></li>
            <li class="active">用户角色</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
<div class="box box-primary">

<?php
    Html::showFlash();
?>

    <p>
        当前用户: <span class="label label-success">电子邮箱：<?php echo $tpl['user_info']['email']; ?></span>
        <span class="label label-info">昵称：<?php echo $tpl['user_info']['nickname']; ?></span>
    </p>
  <div>
    <form class="form-inline" action="/admin/rbac_users_assign" method="post">
        <input type="hidden" name="uid" value="<?php echo $tpl['user_info']['id']; ?>" />

<?php
foreach ($tpl['all_roles'] as $rid => $role_dt)
{
?>
        <div class="checkbox">
            <label>
            <input type="checkbox" name="role_assign[<?php echo $rid?>]" value="<?php echo $rid; ?>" <?php echo in_array($rid, $tpl['user_roles']) ? 'checked' : ''; ?>/>
            <span class="label label-primary"><?php echo $role_dt['description']; ?></span>
            (<?php echo $role_dt['title']; ?>)&nbsp;
            </label>
            &nbsp;&nbsp;
        </div>
<?php
}
?>
        <button type="submit" class="btn btn-default">确认</button>
    </form>
  </div>
</div>
    </section>
</div>
<!-- /.content-wrapper -->

<!--footer-->
<?php
echo Yaf_View_Simple::render('admin/tpl/footer.phtml');
?>
