<!--header-->
<?php
echo Yaf_View_Simple::render('admin/tpl/header.phtml');
?>
<!--/header-->
<!--navbar-->
<?php
echo Yaf_View_Simple::render('admin/tpl/navbar.phtml');
?>
<!--navbar-->

<!-- Left side column. contains the logo and sidebar -->
<!--sidebar-->
<?php
echo Yaf_View_Simple::render('admin/tpl/sidebar.phtml');
?>
<!--sidebar-->

<!-- Right side column. Contains the navbar and content of the page -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            角色
            <small></small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 首页</a></li>
            <li><a href="#">查看角色</a></li>
            <li class="active">角色列表</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

<p>
<?php
    Html::showFlash();
?>
</p>

    <div>
        <table class="table table-striped">
              <thead>
                <tr>
                  <th>角色名</th>
                  <th>角色职能描述</th>
                  <th>操作</th>
                </tr>
              </thead>
              <tbody>

<?php
foreach ($roles as $rl)
{
?>
                <tr>
                  <th scope="row">
                    <?php echo $rl['title']; ?>
                  </th>
                  <td><?php echo $rl['description']; ?></td>
                  <td>
                    <a href="/admin/rbac_roles_edit?rid=<?php echo $rl['rid']; ?>">编辑</a>&nbsp;|&nbsp;
                    <a href="/admin/rbac_roles_manage?rid=<?php echo $rl['rid']; ?>">管理授权</a>&nbsp;|&nbsp;
                    <a href="/admin/rbac_roles_remove?rid=<?php echo $rl['rid']; ?>">删除</a>
                  </td>
                </tr>
<?php
}
?>
              </tbody>
        </table>
    </div>

    <form class="form-inline" action="/admin/rbac_roles_add" method="post">
      <div class="form-group">
        <label for="title">角色</label>
        <input type="text" class="form-control" name="title" id="title" placeholder="create_roles">
      </div>
      <div class="form-group">
        <label for="description">角色职能描述</label>
        <input type="text" class="form-control" name="description" id="description" placeholder="权限的中文描述">
      </div>
      <button type="submit" class="btn btn-default">新增角色</button>
    </form>
    </section>
</div>
<!-- /.content-wrapper -->

<!--footer-->
<?php
echo Yaf_View_Simple::render('admin/tpl/footer.phtml');
?>
