<!--header-->
<?php
echo Yaf_View_Simple::render('second_view/tpl/header.phtml',
    array(
    'css' => array(
        '/static/second_asset/css/about.css',
        '/static/second_asset/common/color.css'
        )
    )
);
?>

<!--nav-->
<?php
echo Yaf_View_Simple::render('second_view/tpl/nav.phtml');
?>

<!--content-->
<div class="row-space-4 row-space-top-6"></div>
<div id="content">
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-sm-6">
                <div class="sidenav">
                    <ul class="sidenav-list hide-sm">
                        <li>
                            <a class="sidenav-item" href="/about/about-us" aria-selected="true">
                                关于我们
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-10 col-sm-6">
                <div class="text-copy">
                    <h1 class="h2 row-space-4">关于我们</h1>
                    <p>
                        农曲星成立于2015年3月，总部位于北京市海淀区。农曲星是一个值得信赖的社区市场，在这里人们可以通过网站或手机发布、发掘和预订您感兴趣的农业产品。
                    </p>
                    <p class="row-space-4">
                        我们致力于生态农业的开发与研究,成员多是来自中国农业大学的大学生.我们有先进的科学理论,扎实的动手能力,努力打造一个全新的现代化的农业平台.
                    </p>

                    <div class="row  row-space-4">
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <!-- About company inner items -->
                            <div class="about-company-inner">
                                <!-- Paragraph with icon -->
                                <span class="company-feature"><i class="fa fa-building-o br-red"></i> <b class="red">3</b> 农场</span>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <!-- About company inner items -->
                            <div class="about-company-inner">
                                <!-- Paragraph with icon -->
                                <span class="company-feature"><i class="fa fa-trophy br-lblue"></i> <b class="lblue">2</b> 奖项</span>
                            </div>
                        </div>
                        <div class="clearfix visible-xs"></div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <!-- About company inner items -->
                            <div class="about-company-inner">
                                <!-- Paragraph with icon -->
                                <span class="company-feature"><i class="fa fa-users br-green"></i> <b class="green">40</b> 伙伴</span>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6 col-xs-6">
                            <!-- About company inner items -->
                            <div class="about-company-inner">
                                <!-- Paragraph with icon -->
                                <span class="company-feature"><i class="fa fa-shopping-cart br-purple"></i> <b class="purple">21</b> 交易</span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<!--footer-->
<?php
echo Yaf_View_Simple::render('second_view/tpl/footer.phtml');
?>