

<!--header-->
<?php
$css = array(
    'css' => array(
        '/static/second_asset/css/about.css',
        '/static/second_asset/common/color.css',
        '/static/second_asset/css/detail.css',
    )
);
echo Yaf_View_Simple::render('second_view/tpl/header.phtml', $css);
?>

<!--nav-->
<?php
echo Yaf_View_Simple::render('second_view/tpl/nav.phtml');
?>

<div class="with-photos<?=(true == $is_mobile) ? ' hide' : ''?>" style="">
    <div class="media-photo media-photo-block discovery-hero">
        <div class="row row-table row-full-height" style="background-image:url(/static/second_asset/img/yingtao2.png);">
            <div class="col-middle text-center text-contrast panel-body" style="width: 100%;margin-top: 40px;">
                <div class="h1 row-space-1">五月凤凰岭樱桃节,"樱"你而精彩!</div>
                <div class="text-lead row-space-2">近千亩优质樱桃,期待您的光临</div>
            </div>
        </div>
    </div>
</div>

<!--
<div id="photos" class="with-photos with-modal<?=(true == $is_mobile) ? ' hide' : ''?>">
    <img src="https://a0.muscache.com/ic/pictures/32626612/22c92586_original.jpg?interpolation=lanczos-none&amp;size=large&amp;output-format=jpg&amp;output-quality=70" class="hide" srcset="https://a0.muscache.com/ic/pictures/32626612/22c92586_original.jpg?interpolation=lanczos-none&amp;size=large&amp;output-format=jpg&amp;output-quality=70 639w, https://a0.muscache.com/ic/pictures/32626612/22c92586_original.jpg?interpolation=lanczos-none&amp;size=xx_large&amp;output-format=jpg&amp;output-quality=70 1440w">
    <span class="cover-img-container" data-hook="cover-img-container">
      <div class="cover-img show-sm" data-hook="img-sm" style="background-image: url(/static/second_asset/img/detail_banner.jpg);">
      </div>
    </span>
</div>
-->

<!--content-->
<div class="row-space-4 row-space-top-6"></div>
<div id="content" class="panel room-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="row-space-4 row-space-top-4">
                    <div class="row">
                        <div class="col-md-2 text-center" style="display: none;">
                            <a href="#host-profile" class="media-photo media-round" style="display: none">
                                <img alt="Catrina" class="host-profile-image" height="90" nopin="nopin" src="" title="Catrina" width="90">
                            </a>
                        </div>
                        <div class="col-md-10">
                            <h1 itemprop="name" class="overflow h3 row-space-1 text-center-sm" id="listing_name">
                                <?=$good['title']?><?=htmlspecialchars($good['slogan'])?>
                            </h1>
                        <span class="hide" itemprop="breadcrumb">
                        <span itemscope="">
                        <a href="#" itemprop="url"><span itemprop="title">聂各庄</span>,</a>
                        </span>
                        <span itemscope="">
                        <a href="#" itemprop="url"><span itemprop="title">海淀区</span>,</a>
                        </span>
                        <span itemscope="">
                        <a href="#" itemprop="url"><span itemprop="title">北京</span></a>
                        </span>
                        </span>
                            <div id="display-address" class="row-space-2 text-muted hide-sm" itemprop="aggregateRating" itemscope="" itemtype="" data-location="">
                                <a href="#neighborhood" class="link-reset"><?=$shop['address']?></a> &nbsp;
                                <a href="#reviews" class="link-reset hide">
                                    <div class="star-rating">
                                        <div class="foreground">
                                            <i class="icon icon-beach fa fa-star"></i>
                                            <i class="icon icon-beach fa fa-star"></i>
                                            <i class="icon icon-beach fa fa-star"></i>
                                            <i class="icon icon-beach fa fa-star"></i>
                                            <i class="icon icon-beach fa fa-star"></i>
                                            <meta itemprop="ratingValue" content="5.0">
                                        </div>
                                    </div>
                                    (<span itemprop="reviewCount">48</span>)
                                </a>
                            </div>
                            <div style="display: none;" class="row row-condensed text-muted text-center">
                                <div class="col-sm-3">
                                    <i class="icon icon-city icon-size-2"></i>
                                </div>
                                <div class="col-sm-3">
                                    <i class="icon icon-group icon-size-2"></i>
                                </div>
                                <div class="col-sm-3">
                                    <i class="icon icon-rooms icon-size-2"></i>
                                </div>
                                <div class="col-sm-3">
                                    <i class="icon icon-double-bed icon-size-2"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4" style="/* display: none; */">
                <div id="tax-descriptions-tip" class="tooltip tooltip-top-middle">
                </div>

                <form accept-charset="UTF-8" action="<?=$good['discount_price'] > 0 ? htmlspecialchars($good['order_url']) : ''?>" class="info new-o2-form-inline" id="book_it_form" method="post" style="display: block;">
                    <div style="margin:0;padding:0;display:inline">
                        <input name="discount_price" type="hidden" value="<?=$good['discount_price']?>">
                        <input name="good_id" type="hidden" value="<?=$good['encode_good_id']?>">
                        <input name="good_num" type="hidden" value="<?=1?>">
                        <input name="auth_token" type="hidden" value="<?=time()?>">
                    </div>
                    <div id="pricing" class="">
                        <div id="price_amount" itemprop="price" class="pull-left h3 text-special">¥ <?=htmlspecialchars($good['discount_price'])?>/<?=htmlspecialchars($good['unit'])?></div>
                        <div id="payment-period-container" class="pull-right" style="display: none;">
                            <div id="per_night" class="">
                                每晚
                            </div>
                        </div>
                        <meta content="USD" itemprop="priceCurrency">
                    </div>
                    <div id="book_it" class="" style="top: 0px;">
                        <div class="panel">
                            <div class="panel-body panel-light">
                                <p itemprop="name" class="row-space-1 row-space-2 h4 vip_panel" id="listing_name">
                                    <?=htmlspecialchars($good['title'])?>
                                </p>
                                <div class="row">
                                    <div class="col-md-3 own_info">
                                        <p itemprop="name" class="row-space-1 vip_panel" id="listing_name">
                                            <i class="fa fa-user br-purple"></i><?=htmlspecialchars($good['contactor'])?>
                                        </p>
                                    </div>
                                    <div class="col-md-3 own_info">
                                        <p itemprop="name" class="row-space-1 vip_panel" id="listing_name">
                                            <i class="fa fa-phone br-purple"></i><?=htmlspecialchars($good['phone'])?>
                                        </p>
                                    </div>
                                    <div class="col-md-3 own_info">
                                        <p itemprop="name" class="row-space-1 vip_panel" id="listing_name">
                                            <i class="fa fa-map-marker br-purple"></i><?=htmlspecialchars($shop['address'])?>
                                        </p>
                                    </div>
                                    <div class="col-md-3 own_info">
                                        <p itemprop="name" class="row-space-1 vip_panel" id="listing_name">
                                            <i class="fa fa-eye br-purple"></i>共<?=isset($visit_pv) ? $visit_pv : 0?>人查看了
                                        </p>
                                    </div>

                                </div>
                                <?php if($good['discount_price'] > 0){?>
                                <div id="book_it_status" style="">
                                    <div id="book_it_enabled" class="clearfix">
                                        <div id="book_it_button_container" class="row-space-top-2">
                                            <?php if(isset($_is_login_) && true === $_is_login_){?>
                                                <?php if(isset($can_buy) && true == $can_buy) {?>
                                                    <?php if($good['stock'] <= 0){ ?>
                                                        <a href="javascript:void(0)" des="库存不足" style="font-size: 16px;padding: 9px 27px;" class="btn btn-warning btn-large btn-block" id="book_it_button">
                                                            <span class="book-it">库存不足</span>
                                                        </a>
                                                    <?php }else{ ?>
                                                        <button type="submit" des="正常购买" class="btn btn-applay btn-large btn-block" id="book_it_button">
                                                            <span class="book-it">立即购买</span>
                                                        </button>
                                                    <?php } ?>

                                                <?php }else{?>
                                                    <a href="javascript:void(0)" des="限购" style="font-size: 16px;padding: 9px 27px;" class="btn btn-warning btn-large btn-block" id="book_it_button">
                                                        <span class="book-it">限购商品,您已经购买过了</span>

                                                    </a>
                                                <?php }?>
                                            <?php }else{?>

                                            <button type="button" des="没有登录" class="btn btn-applay btn-large btn-block" data-toggle="modal" data-target=".login_model">
                                                <span class="book-it">立即购买</span>
                                            </button>
                                            <?php }?>
                                        </div>
                                    </div>
                                </div>
                                <?php }?>
                                
                                <!--share to sns-->
                                <?php if(isset($share) && $share){?>
                                <div class="other-actions hide-sm text-center">
                                    <div class="social-share-widget row-space-top-3">
                                        <span class="share-title">分享：</span>
                                                <span class="share-triggers">
                                                    <?php
                                                        $share_data = '?' . 'title=' .urlencode($share['title']) . '&url=' . urlencode($share['url']) . '&pic='.urlencode($share['pic']);
                                                    ?>                                               
                                                  <a class="share-btn" data-network="weibo" href="http://service.weibo.com/share/share.php<?=$share_data?>" title="新浪微博分享" rel="nofollow" target="_blank">
                                                      <i class="fa fa-weibo icon-gray social-icon-size"></i>
                                                  </a>
                                                </span>
                                    </div>
                                </div>
                                <?php }?>
                            </div>
                        </div>
                        <?php if($shop['long'] && $shop['lat']){?>
                        <!--<img class="map-canvas" src="https://maps.googleapis.com/maps/api/staticmap?center=37.774771731719326%2C-122.4205836605131&amp;zoom=10&amp;size=314x214&amp;client=gme-airbnbinc&amp;channel=monorail-prod&amp;signature=ui4vfsQk7SBWRmhhZ1q3lyPgZ2g%3D">-->
                        <div class="shop_map" id="shop_map" long="<?=htmlspecialchars($shop['long'])?>" lat="<?=htmlspecialchars($shop['lat'])?>">

                        </div>
                        <?php }?>
                    </div>

                </form>
            </div>
        </div>
    </div>

</div>

<!--detail-->
<div id="detail">
    <div class="container">
        <div class="row">
            <div class="col-lg-8" style="">
                <div class=row-space-top-8">
                    <h4 class="row-space-4 new-tit">
                        <span class="name">关于店家</span>
                    </h4>
                    <div class="panel panel-dark row-space-4">
                        <div class="panel-body"><?=$shop['describe']?></div>
                    </div>



                    <?php if(isset($good['photo']) && $good['photo']){?>
                    <h4 class="row-space-4 new-tit">
                        <span class="name">产品产示</span>
                    </h4>
                    <div class="panel panel-dark row-space-4 good_imgs">
                        <?php foreach((array)$good['photo'] as $key => $img){?>
                        <div class="<?=($key !== 0) ? 'row-space-top-3 ' : ''?>">
                            <img class="lazy" src="/static/default/default_img.png" data-original="<?=$img?>"></div>
                        <?php }?>
                    </div>
                    <?php }?>

                    <?php if(isset($good['buy_needKnow']) && $good['buy_needKnow']){?>
                    <h4 class="row-space-4 new-tit">
                        <span class="name">用户须知</span>
                    </h4>
                    <div class="panel panel-dark row-space-4 good_imgs">
                         <div class="" style="padding-top: 15px;"><?=$good['buy_needKnow']?></div>
                    </div>
                    <?php }?>


                    <?php if(isset($good['buy_detail'])) {?>
                        <h4 class="row-space-4 new-tit">
                            <span class="name">购买详情</span>
                        </h4>
                        <div class="panel panel-dark row-space-4 good_imgs">
                            <div class="" style="padding-top: 15px;"><?=$good['buy_detail']?></div>
                        </div>
                    <?php }?>

                    <?php if(isset($good['use_list'])) {?>
                        <h4 class="row-space-4 new-tit">
                            <span class="name">使用流程</span>
                        </h4>
                        <div class="panel panel-dark row-space-4 good_imgs">
                            <div class="" style="padding-top: 15px;"><?=$good['use_list']?></div>
                        </div>
                    <?php }?>

                    <!--comment-->
                        <h4 class="row-space-4 new-tit">
                            <span class="name">用户评论</span>
                        </h4>

                        <div class="panel panel-dark row-space-4 good_imgs">
                            <div class="row">
                                <div class="col-md-11">
                                    <div class="row-space-8 row-space-top-8">

                                    </div>
                                    <div class="review-content">
                                        <div class="panel-body">

                                            <div id="comment_down"></div>

                                            <div class="row">
                                                <div class="col-lg-9 col-md-offset-3">
                                                    <p class="">
                                                        暂无评论
                                                    </p>
                                                    <button style="display: none;" class="btn btn-default" page="1" id="more_comment" has_next="true" max_oid="0" oid="<?=htmlspecialchars($good['encode_good_id'])?>">查看其他评价</button>
                                                </div>
                                            </div>

                                            <?php if(isset($_is_login_) && true == $_is_login_){ ?>
                                            <div class="row row-space-top-1">
                                                <div class="col-md-9 col-md-push-3">
                                                    <hr>
                                                </div>
                                                <div class="col-lg-9 col-md-offset-3">
                                                    <textarea class="form-control" rows="3" placeholder="我也要评论..." id="word_text"></textarea>
                                                    <p><span class="pull-right" style="font-size: 11px;color: #ccc;" id="word_count">800个字</span></p>
                                                </div>

                                                <div class="col-lg-9 col-md-offset-3 row-space-top-2">
                                                    <button type="button" class="btn btn-success btn-sm" oid="<?=htmlspecialchars($good['encode_good_id'])?>" id="add_comment">提交</button>
                                                </div>
                                            </div>
                                            <?php }?>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <!--comment-->


                </div>
            </div>
        </div>
    </div>
</div>

<!--reco-->
<?php if(isset($recommend) && is_array($recommend) && !empty($recommend)){?>
<div id="recommend" class="container">
    <h4 class="row-space-4 text-center-sm row-space-top-8">
        为您推荐
    </h4>
    <div class="row">
        <div class="col-md-4">
            <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                <div class="panel-image listing-img">
                    <a href="/rooms/764010" class="media-photo media-cover" target="_self">
                        <div class="listing-img-container media-cover text-center">
                            <img src="/static/second_asset/img/list.jpg" class="img-responsive-height">
                        </div>
                    </a>
                    <div>
                        <div>
                            <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">
                                <div><sup class="h6 text-contrast">lei</sup><span class="h3 price-amount">304</span><sup class="h6 text-contrast"></sup></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                </div>
                <div class="panel-body panel-card-section">
                    <div class="media">
                        <a href="/rooms/764010" class="text-normal" target="_self">
                            <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1">Classic room in Lower Pac Heights</div>
                        </a>
                        <div class="text-muted listing-location text-truncate">独立房间 · 旧金山</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                <div class="panel-image listing-img">
                    <a href="/rooms/764010" class="media-photo media-cover" target="_self">
                        <div class="listing-img-container media-cover text-center">
                            <img src="/static/second_asset/img/list.jpg" class="img-responsive-height">
                        </div>
                    </a>
                    <div>
                        <div>
                            <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">
                                <div><sup class="h6 text-contrast">lei</sup><span class="h3 price-amount">304</span><sup class="h6 text-contrast"></sup></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                </div>
                <div class="panel-body panel-card-section">
                    <div class="media">
                        <a href="/rooms/764010" class="text-normal" target="_self">
                            <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1">Classic room in Lower Pac Heights</div>
                        </a>
                        <div class="text-muted listing-location text-truncate">独立房间</div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-md-4">
            <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                <div class="panel-image listing-img">
                    <a href="/rooms/764010" class="media-photo media-cover" target="_self">
                        <div class="listing-img-container media-cover text-center">
                            <img src="/static/second_asset/img/list.jpg" class="img-responsive-height">
                        </div>
                    </a>
                    <div>
                        <div>
                            <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label">
                                <div><sup class="h6 text-contrast">lei</sup><span class="h3 price-amount">304</span><sup class="h6 text-contrast"></sup></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                </div>
                <div class="panel-body panel-card-section">
                    <div class="media">
                        <a href="/rooms/764010" class="text-normal" target="_self">
                            <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1">Classic room in Lower Pac Heights</div>
                        </a>
                        <div class="text-muted listing-location text-truncate">独立房间 · 旧金山</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php }?>

<!--footer-->
<?php
$js = array(
    'js' => array(
        'http://api.map.baidu.com/api?v=2.0&ak=T7gDQXp0hmAGKCFol7ktMC2P',
        '/static/plugin/jquery.lazyload.min.js',
        '/static/second_asset/js/detail.js',
    )
);
echo Yaf_View_Simple::render('second_view/tpl/footer.phtml', $js);
?>


<?php if($shop['long'] && $shop['lat']){?>

<script type="text/javascript">
    var map = new BMap.Map("shop_map");            // 创建Map实例
    var point = new BMap.Point(<?=htmlspecialchars($shop['long'])?>, <?=htmlspecialchars($shop['lat'])?>); // 创建点坐标
    map.centerAndZoom(point,15);                 // 初始化地图,设置中心点坐标和地图级别。
    map.addControl(new BMap.MapTypeControl());    //添加地图缩放控件

    var marker = new BMap.Marker(point);  // 创建标注
    map.addOverlay(marker);               // 将标注添加到地图中
    marker.setAnimation(BMAP_ANIMATION_BOUNCE); //跳动的动画

    $(window).resize(function() {
        var window_width = $(window).width();
        if(window_width < 1200 || window_width >= 1200){
            map.centerAndZoom(point,15);
        }
    });

    $("img.lazy").lazyload({ threshold : 200 });

</script>

<?php }?>
