<!--header-->

<?php
echo Yaf_View_Simple::render('second_view/tpl/header.phtml', array('css' => array('/static/second_asset/css/index.css')));
?>

<!--nav-->
<?php
echo Yaf_View_Simple::render('second_view/tpl/nav.phtml');
?>


<div class="row-space-8">
    <div class="media-photo media-photo-block discovery-hero">
        <div class="row row-table row-full-height" style="background-image:url(/static/second_asset/img/index_banner.jpg);">
            <div class="col-middle text-center text-contrast panel-body" style="width: 100%;">
                <div class="h1 row-space-1">北美洲最热门</div>
                <div class="text-lead row-space-2">让Airbnb旅客喜爱的目的地为您带来灵感。</div>
            </div>
        </div>
    </div>
</div>

<div class="container page-container-responsive">
<div module="haidian">
    <div class="row-space-2">
        <span class="h2" data-reactid=".u1lhf97lz4.1.0:$0.0.0.2">海淀区</span>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="pictures discovery-image">
                <img src="/static/second_asset/img/list_first.jpg" class="discovery-image img-responsive">
            </div>
        </div>
        <div class="col-md-4">
            <div class="map-container">
                <div class="row-space-2">
                    <h4>为何来此地旅行？</h4>
                    <p class="text-lead">金门大桥、恶魔岛、高山峻岭、神秘的雾、同性恋游行、波希米亚风、50年代Beatniks文化、梦想家、思想家、科技创始公司、维多利亚式建筑、欧洲风情、近郊徒步、49人队、巨人队、The Wiggle自行车骑行线路、农产品。</p>
                </div>
                <div class="discovery-bottom">
                    <img class="map-canvas" src="https://maps.googleapis.com/maps/api/staticmap?center=37.774771731719326%2C-122.4205836605131&amp;zoom=10&amp;size=314x214&amp;client=gme-airbnbinc&amp;channel=monorail-prod&amp;signature=ui4vfsQk7SBWRmhhZ1q3lyPgZ2g%3D" >
                </div>
            </div>
        </div>
    </div>

    <div class="row-space-8"></div>
    <!--list 3 items-->
    <div class="row">
        <div class="col-md-4">
            <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                <div class="panel-image listing-img">
                    <a href="/rooms/764010" class="media-photo media-cover" target="_self">
                        <div class="listing-img-container media-cover text-center">
                            <img src="/static/second_asset/img/list.jpg" class="img-responsive-height">
                        </div>
                    </a>
                    <div>
                        <div>
                            <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label" >
                                <div><sup class="h6 text-contrast">lei</sup><span class="h3 price-amount">304</span><sup class="h6 text-contrast"></sup></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                </div>
                <div class="panel-body panel-card-section">
                    <div class="media">
                        <a href="/rooms/764010" class="text-normal" target="_self">
                            <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1">Classic room in Lower Pac Heights</div>
                        </a>
                        <div class="text-muted listing-location text-truncate">独立房间 · 旧金山</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                <div class="panel-image listing-img">
                    <a href="/rooms/764010" class="media-photo media-cover" target="_self">
                        <div class="listing-img-container media-cover text-center">
                            <img src="/static/second_asset/img/list.jpg" class="img-responsive-height">
                        </div>
                    </a>
                    <div>
                        <div>
                            <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label" >
                                <div><sup class="h6 text-contrast">lei</sup><span class="h3 price-amount">304</span><sup class="h6 text-contrast"></sup></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                </div>
                <div class="panel-body panel-card-section">
                    <div class="media">
                        <a href="/rooms/764010" class="text-normal" target="_self">
                            <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1">Classic room in Lower Pac Heights</div>
                        </a>
                        <div class="text-muted listing-location text-truncate">独立房间 · 旧金山</div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-md-4">
            <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                <div class="panel-image listing-img">
                    <a href="/rooms/764010" class="media-photo media-cover" target="_self">
                        <div class="listing-img-container media-cover text-center">
                            <img src="/static/second_asset/img/list.jpg" class="img-responsive-height">
                        </div>
                    </a>
                    <div>
                        <div>
                            <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label" >
                                <div><sup class="h6 text-contrast">lei</sup><span class="h3 price-amount">304</span><sup class="h6 text-contrast"></sup></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                </div>
                <div class="panel-body panel-card-section">
                    <div class="media">
                        <a href="/rooms/764010" class="text-normal" target="_self">
                            <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1">Classic room in Lower Pac Heights</div>
                        </a>
                        <div class="text-muted listing-location text-truncate">独立房间 · 旧金山</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--view more-->
    <div class="row row-space-6" >
        <div class="col-md-4 col-center hide-md">
            <a class="btn btn-large btn-block see-available-items" href="/s/New-York--NY--US">查看所有可供出租的房源</a>
        </div>
    </div>
</div>

<div module="changping">
    <div class="row-space-2">
        <span class="h2" data-reactid=".u1lhf97lz4.1.0:$0.0.0.2">昌平区</span>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="pictures discovery-image">
                <img src="/static/second_asset/img/list_first.jpg" class="discovery-image img-responsive">
            </div>
        </div>
        <div class="col-md-4">
            <div class="map-container">
                <div class="row-space-2">
                    <h4>为何来此地旅行？</h4>
                    <p class="text-lead">金门大桥、恶魔岛、高山峻岭、神秘的雾、同性恋游行、波希米亚风、50年代Beatniks文化、梦想家、思想家、科技创始公司、维多利亚式建筑、欧洲风情、近郊徒步、49人队、巨人队、The Wiggle自行车骑行线路、农产品。</p>
                </div>
                <div class="discovery-bottom">
                    <img class="map-canvas" src="https://maps.googleapis.com/maps/api/staticmap?center=37.774771731719326%2C-122.4205836605131&amp;zoom=10&amp;size=314x214&amp;client=gme-airbnbinc&amp;channel=monorail-prod&amp;signature=ui4vfsQk7SBWRmhhZ1q3lyPgZ2g%3D" >
                </div>
            </div>
        </div>
    </div>

    <div class="row-space-8"></div>
    <!--list 3 items-->
    <div class="row">
        <div class="col-md-4">
            <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                <div class="panel-image listing-img">
                    <a href="/rooms/764010" class="media-photo media-cover" target="_self">
                        <div class="listing-img-container media-cover text-center">
                            <img src="/static/second_asset/img/list.jpg" class="img-responsive-height">
                        </div>
                    </a>
                    <div>
                        <div>
                            <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label" >
                                <div><sup class="h6 text-contrast">lei</sup><span class="h3 price-amount">304</span><sup class="h6 text-contrast"></sup></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                </div>
                <div class="panel-body panel-card-section">
                    <div class="media">
                        <a href="/rooms/764010" class="text-normal" target="_self">
                            <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1">Classic room in Lower Pac Heights</div>
                        </a>
                        <div class="text-muted listing-location text-truncate">独立房间 · 旧金山</div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                <div class="panel-image listing-img">
                    <a href="/rooms/764010" class="media-photo media-cover" target="_self">
                        <div class="listing-img-container media-cover text-center">
                            <img src="/static/second_asset/img/list.jpg" class="img-responsive-height">
                        </div>
                    </a>
                    <div>
                        <div>
                            <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label" >
                                <div><sup class="h6 text-contrast">lei</sup><span class="h3 price-amount">304</span><sup class="h6 text-contrast"></sup></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                </div>
                <div class="panel-body panel-card-section">
                    <div class="media">
                        <a href="/rooms/764010" class="text-normal" target="_self">
                            <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1">Classic room in Lower Pac Heights</div>
                        </a>
                        <div class="text-muted listing-location text-truncate">独立房间 · 旧金山</div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-md-4">
            <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                <div class="panel-image listing-img">
                    <a href="/rooms/764010" class="media-photo media-cover" target="_self">
                        <div class="listing-img-container media-cover text-center">
                            <img src="/static/second_asset/img/list.jpg" class="img-responsive-height">
                        </div>
                    </a>
                    <div>
                        <div>
                            <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label" >
                                <div><sup class="h6 text-contrast">lei</sup><span class="h3 price-amount">304</span><sup class="h6 text-contrast"></sup></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                </div>
                <div class="panel-body panel-card-section">
                    <div class="media">
                        <a href="/rooms/764010" class="text-normal" target="_self">
                            <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1">Classic room in Lower Pac Heights</div>
                        </a>
                        <div class="text-muted listing-location text-truncate">独立房间 · 旧金山</div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--view more-->
    <div class="row row-space-6" >
        <div class="col-md-4 col-center hide-md">
            <a class="btn btn-large btn-block see-available-items" href="/s/New-York--NY--US">查看所有可供出租的房源</a>
        </div>
    </div>
</div>
</div>


<!--footer-->
<?php
echo Yaf_View_Simple::render('second_view/tpl/footer.phtml');
?>