<!--header-->

<?php
echo Yaf_View_Simple::render('second_view/tpl/header.phtml', array('css' => array('/static/second_asset/css/index.css')));
?>

<!--nav-->
<?php
echo Yaf_View_Simple::render('second_view/tpl/nav.phtml');
?>


<div class="row-space-8">
    <div class="media-photo media-photo-block discovery-hero">
        <div class="row row-table row-full-height" style="background-image:url(/static/second_asset/img/index_banner.png);">
            <div class="col-middle text-center text-contrast panel-body" style="width: 100%;">
                <div class="h1 row-space-1">春光无限好,你为何宅在家!</div>
                <div class="text-lead row-space-2">来周边走走吧,感受下采摘的乐趣</div>
            </div>
        </div>
    </div>
</div>

<div class="container page-container-responsive">
    <?php foreach($response as $dis => $goods){?>
    <div module="haidian">
        <div class="row-space-2">
            <span class="h2"><?=$districts[$dis]['name']?>区</span>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="pictures discovery-image">
                    <img src="<?=$districts[$dis]['pic']?>" class="discovery-image img-responsive">
                </div>
            </div>
            <div class="col-md-4">
                <div class="map-container">
                    <div class="row-space-2">
                        <h4>为何来要来这里？</h4>
                        <p class="text-lead"><?=$districts[$dis]['des']?></p>
                    </div>
                    <div class="discovery-bottom">
                        <img class="map-canvas" src="<?=$districts[$dis]['map_img']?>">
                    </div>
                </div>
            </div>
        </div>

        <div class="row-space-8"></div>
        <!--list 3 items-->
        <div class="row">
            <?php foreach($goods as $key =>$good){
                if($key >= 3) break;
                if(!is_array($good)) continue;
            ?>
            <div class="col-md-4">
                <div data-lat="37.78213221257644" data-lng="-122.44787046023013" data-name="Classic room in Lower Pac Heights" data-url="/rooms/764010" data-id="764010" class="listing" itemtype="http://schema.org/Enumeration">
                    <div class="panel-image listing-img">
                        <a href="<?=$good['detail_url']?>" class="media-photo media-cover" target="_blank">
                            <div class="listing-img-container media-cover text-center">
                                <img class="lazy" src="/static/default/default_img.png" data-original="<?=$good['photo'][0]?>" class="img-responsive-height">
                            </div>
                        </a>
                        <div>
                            <div>
                                <div class="panel-overlay-bottom-left panel-overlay-label panel-overlay-listing-label" >
                                    <div><sup class="h6 text-contrast">¥</sup><span class="h3 price-amount"><?=htmlspecialchars($good['price'])?></span><sup class="h6 text-contrast"></sup></div>
                                </div>
                            </div>
                        </div>
                        <div class="panel-overlay-top-right wl-social-connection-panel"></div>
                    </div>
                    <div class="panel-body panel-card-section">
                        <div class="media">
                            <a href="<?=$good['detail_url']?>" class="text-normal" target="_self">
                                <div title="Classic room in Lower Pac Heights" class="h5 listing-name text-truncate row-space-top-1"><?=htmlspecialchars($good['title'])?></div>
                            </a>
                            <div class="text-muted listing-location text-truncate"><?=htmlspecialchars($good['address'])?></div>
                        </div>
                    </div>
                </div>
            </div>
            <?php }?>

        </div>

        <!--view more-->
        <div class="row row-space-6 <?=(count($goods) <= 3 ? 'hide' : '')?>" >
            <div class="col-md-4 col-center hide-md">
                <a class="btn btn-large btn-block see-available-items" href="<?=htmlspecialchars($goods['view_more'])?>">查看更多信息</a>
            </div>
        </div>
    </div>

    <?php }?>


</div>


<!--footer-->
<?php
$js = array(
    'js' => array(
        '/static/plugin/jquery.lazyload.min.js',
    )
);
echo Yaf_View_Simple::render('second_view/tpl/footer.phtml', $js);
?>

<script type="text/javascript">

    $("img.lazy").lazyload({ threshold : 200 });

</script>