<!-- Header Start -->
<?php
  echo Yaf_View_Simple::render('tpl/header.phtml', array('cssArr'=>array('sy.css')));
?>
<!-- Header End -->

<!-- Nav Start -->
<?php
  echo Yaf_View_Simple::render('tpl/nav.phtml', array('currentNav'=>'home'));
?>
<!-- Nav End -->

<!-- Page Wrapper -->
<div class="wrapper">
  <!-- Slider Start
  #################################
    - THEMEPUNCH BANNER -
  ################################# -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class=""></li>
          <li data-target="#myCarousel" data-slide-to="1" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <div class="item">
            <img src="static/imgs/slide2.jpg" alt="First slide">
            <div class="container">
              <div class="carousel-caption">
                <h1 class="slideTitle">木木家柴鸡蛋</h1>
                <p>大学生自主创业,凤凰岭三十亩有机农场,一千只散养柴鸡.</p>
                <p><a class="btn btn-lg btn-success" href="#" role="button">子解更多</a></p>
              </div>
            </div>
          </div>
          <div class="item active">
            <img src="static/imgs/slide2.jpg" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1 class="slideTitle">李阿姨柴鸡蛋</h1>
                <p>果园农场散养柴鸡蛋 绿色有机无污染</p>
                <p><a class="btn btn-lg btn-success" href="#" role="button">子解更多</a></p>
              </div>
            </div>
          </div>
          <div class="item">
            <img src="static/imgs/slide2.jpg" alt="Third slide">
            <div class="container">
              <div class="carousel-caption">
                <h1 class="slideTitle">农业大学生态鸡蛋</h1>
                <p>中国农业大学生态鸡蛋实验基地,科学养殖,营养价值高</p>
                <p><a class="btn btn-lg btn-success" href="#" role="button">了解更多</a></p>
              </div>
            </div>
          </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
  </div>

  <!-- Slider End -->



  <!-- Main Content -->
  <div class="main-content">
    <!-- Showcase Start -->
    <div class="showcase">
      <div class="container">

        <!-- Default Heading -->
        <div class="default-heading">
          <!-- Crown image -->
          <!--<img class="img-responsive" src="img/crown.png" alt="" />-->
          <!-- Heading -->
          <h2>特色农家乐</h2>
          <!-- Paragraph -->
          <p>北京周边一日游住宿  朋友聚会 生日Party 家庭聚会</p>
          <!-- Border -->
          <div class="border"></div>
        </div>

        <div class="row">
          <div class="col-md-6 col-sm-6">
            <!-- Showcase section item -->
            <div class="showcase-item">
              <!-- Image -->
              <img class="img-responsive" src="/static/imgs/fruit2.png" alt="" />
              <!-- Heading -->
              <h3><a href="#">中国农业大学烧烤乐园</a></h3>
              <!-- Paragraph -->
              <p>中国农业大学生态鸡蛋培育基地,主要培育散养柴鸡,柴鸡蛋,200平方米开阔烧烤乐园,等候您的光临.</p>
              <div class="clearfix"></div>
            </div>
          </div>
          <div class="col-md-6 col-sm-6">
            <!-- Showcase section item -->
            <div class="showcase-item">
              <!-- Image -->
              <img class="img-responsive" src="/static/imgs/fruit3.png" alt="" />
              <!-- Heading -->
              <h3><a href="#">木木家生态烧烤基地</a></h3>
              <!-- Paragraph -->
              <p>大学生创业养殖产业,30亩林地玩出新花样,1000只柴鸡,1000平米烧烤平台,让您一次玩个痛快.</p>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Showcase End -->

    <!-- Dishes Start -->
    <div class="dishes padd">
      <div class="container">
        <!-- Default Heading -->
        <div class="default-heading">
          <!-- Crown image -->
          <!--<img class="img-responsive" src="img/crown.png" alt="" />-->
          <!-- Heading -->
          <h2>散养柴鸡蛋</h2>
          <!-- Paragraph -->
          <p>养柴鸡蛋 营养好 有机绿色产品无污染 </p>
          <!-- Border -->
          <div class="border"></div>
        </div>
        <div class="row">
          <div class="col-md-3 col-sm-6">
            <div class="dishes-item-container">
              <!-- Image Frame -->
              <div class="img-frame">
                <!-- Image -->
                <img src="/static/imgs/dish5.jpg" class="img-responsive" alt="" />
                <!-- Block for on hover effect to image -->
                <div class="img-frame-hover">
                  <!-- Hover Icon -->
                  <a href="#"><i class="fa fa-info-circle"></i></a>
                </div>
              </div>
              <!-- Dish Details -->
              <div class="dish-details">
                <!-- Heading -->
                <h3>李阿姨柴鸡蛋</h3>
                <!-- Paragraph -->
                <p>果园农场散养柴鸡蛋 绿色有机无污染</p>
                <p>地点:北京市海淀区凤凰岭聂各庄</p>
                <!-- Button -->
                <a href="#" class="btn btn-success btn-sm">查看更多</a>
              </div>
            </div>
          </div>
          <div class="col-md-3 col-sm-6">
            <div class="dishes-item-container">
              <!-- Image Frame -->
              <div class="img-frame">
                <!-- Image -->
                <img src="/static/imgs/dish6.jpg" class="img-responsive" alt="" />
                <!-- Block for on hover effect to image -->
                <div class="img-frame-hover">
                  <!-- Hover Icon -->
                  <a href="#"><i class="fa fa-info-circle"></i></a>
                </div>
              </div>
              <!-- Dish Details -->
              <div class="dish-details">
                <!-- Heading -->
                <h3>中国农大生态鸡蛋</h3>
                <!-- Paragraph -->
                <p>中国农业大学生态鸡蛋实验基地,科学养殖,营养价值高 </p>
                <p>地点:北京市海淀区凤凰岭聂各庄</p>
                <!-- Button -->
                <a href="#" class="btn btn-success btn-sm">查看更多</a>
              </div>
            </div>
          </div>
          <div class="col-md-3 col-sm-6">
            <div class="dishes-item-container">
              <!-- Image Frame -->
              <div class="img-frame">
                <!-- Image -->
                <img src="/static/imgs/dish7.jpg" class="img-responsive" alt="" />
                <!-- Block for on hover effect to image -->
                <div class="img-frame-hover">
                  <!-- Hover Icon -->
                  <a href="#"><i class="fa fa-info-circle"></i></a>
                </div>
              </div>
              <!-- Dish Details -->
              <div class="dish-details">
                <!-- Heading -->
                <h3>木木家生态柴鸡蛋</h3>
                <!-- Paragraph -->
                <p>大学生自主创业,凤凰岭三十亩有机农场,一千只散养柴鸡.</p>
                <p>地点:北京市海淀区凤凰岭聂各庄</p>
                <!-- Button -->
                <a href="#" class="btn btn-success btn-sm">查看更多</a>
              </div>
            </div>
          </div>
          <div class="col-md-3 col-sm-6">
            <div class="dishes-item-container">
              <!-- Image Frame -->
              <div class="img-frame">
                <!-- Image -->
                <img src="/static/imgs/dish8.jpg" class="img-responsive" alt="" />
                <!-- Block for on hover effect to image -->
                <div class="img-frame-hover">
                  <!-- Hover Icon -->
                  <a href="#"><i class="fa fa-info-circle"></i></a>
                </div>
              </div>
              <!-- Dish Details -->
              <div class="dish-details">
                <!-- Heading -->
                <h3>杨阿姨家柴鸡蛋</h3>
                <!-- Paragraph -->
                <p>苹果里散养柴鸡,有机绿色无污染,适合孕妇及婴儿.</p>
                <p>地点:北京市海淀区凤凰岭聂各庄(346路公交聂各庄站)</p>
                <!-- Button -->
                <a href="#" class="btn btn-success btn-sm">查看更多</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Dishes End -->
  </div>
  <!-- / Main Content End -->
</div>
<!-- / Wrapper End -->

<!-- Footer Start -->
<?php
  echo Yaf_View_Simple::render('tpl/footer.phtml', array('cssArr'=>array('sy.css')));
?>
<!-- Footer End -->

<script type="text/javascript">
  $('.carousel').carousel({
  interval: 2000
})
</script>
